# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# files in which the hooks will be applied
files: |
    (?x)^(
        invesalius/.*/.*py
        | setup.py
        | app.py
        | typings/.*/.*pyi
    )$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [ -I, --fix ]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]


