name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-22.04 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Force setuptools-scm version
        run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=3.1.0-dev.${{ github.run_number }}" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
                  freeglut3-dev \
                  libcurl4-openssl-dev \
                  libexpat1-dev \
                  libgl1-mesa-dev \
                  libglu1-mesa-dev \
                  libgtk-3-dev \
                  libjpeg-dev \
                  libnotify-dev \
                  libsdl2-dev \
                  libsm-dev \
                  libtiff-dev \
                  libwebkit2gtk-4.0-dev \
                  libxtst-dev \
                  libunwind-dev \
                  libgstreamer1.0-dev \
                  libgstreamer-plugins-base1.0-dev \
                  libpng-dev \
                  libxrandr-dev \
                  libxinerama-dev \
                  libxcursor-dev \
                  libxcomposite-dev \
                  libfreetype6-dev \
                  libxi-dev \
                  build-essential \
                  python3-dev \
                  python3-wheel \
                  python3-pip

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Syncing with UV
        run: uv sync --all-extras

      - name: Run tests with xvfb
        run: xvfb-run -a bash -c "pytest"

      - name: Minimize uv cache
        run: uv cache prune --ci


  combined-checks:
    runs-on: ubuntu-22.04
    needs: [run-tests]
    steps:
      - run: echo "All checks passed! Ready to merge."
