name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-22.04 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Force setuptools-scm version
        run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=3.1.0-dev.${{ github.run_number }}" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
                  freeglut3-dev \
                  libcurl4-openssl-dev \
                  libexpat1-dev \
                  libgl1-mesa-dev \
                  libglu1-mesa-dev \
                  libgtk-3-dev \
                  libjpeg-dev \
                  libnotify-dev \
                  libsdl2-dev \
                  libsm-dev \
                  libtiff-dev \
                  libwebkit2gtk-4.0-dev \
                  libxtst-dev \
                  libunwind-dev \
                  libgstreamer1.0-dev \
                  libgstreamer-plugins-base1.0-dev \
                  libpng-dev \
                  libxrandr-dev \
                  libxinerama-dev \
                  libxcursor-dev \
                  libxcomposite-dev \
                  libfreetype6-dev \
                  libxi-dev \
                  libgtk-3-0 \
                  libgl1-mesa-glx \
                  libgstreamer-plugins-good1.0-0 \
                  libgstreamer-plugins-bad1.0-0 \
                  libgstreamer-plugins-ugly1.0-0 \
                  libpulse-dev


      - uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Syncing with UV
        run: uv sync --all-extras --find-links https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04

      - name: Run tests with xvfb
        run: xvfb-run -a bash -c "pytest"

      - name: Minimize uv cache
        run: uv cache prune --ci


  combined-checks:
    runs-on: ubuntu-22.04
    needs: [run-tests]
    steps:
      - run: echo "All checks passed! Ready to merge."
